columnSuffix: null
handle: images
instructions: null
name: Images
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
    - video
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:a721f4bf-2498-48e1-a195-19ca20f08c62' # Imagery
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:a721f4bf-2498-48e1-a195-19ca20f08c62' # Imagery
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
