#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    summit-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "summit-redirectHttps"
    summit-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "summit-redirectHttps"
    summit-web-3000-http:
      entrypoints:
        - http-3001
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-web-3000"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "summit-redirectHttps"
    summit-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "summit-redirectHttps"
    
    
    
    
    summit-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-web-80"
      ruleSyntax: v3
      
      tls: true
      
    summit-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    summit-web-3000-https:
      entrypoints:
        - http-3000
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-web-3000"
      ruleSyntax: v3
      
      tls: true
      
    
    summit-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^summit\.ddev\.site$`)
      
      service: "summit-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    summit-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    summit-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-summit-web:80
        
    summit-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-summit-web:8025
        
    summit-web-3000:
      loadbalancer:
        servers:
          - url: http://ddev-summit-web:3000
        
    
    
    
    summit-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-summit-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/summit.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/summit.key